version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000

      # Seeding Configuration
      BACKDOOR_ENABLED: "true"
      BACKDOOR_USERNAME: example@gmail.com
      BACKDOOR_PASSWORD: password

      # Database Configuration
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: portfoliodb
      DB_HOST: db
      DB_PORT: 5432

      # JWT Configuration
      JWT_SECRET: mySecretKeyIdontWantToKeep
      JWT_EXPIRES_IN: 5h

      # Swagger Configuration
      swaggerEnabled: "true"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    networks:
      - internal

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfoliodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    networks:
      - internal

networks:
  internal:
    driver: overlay
